baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Scotws's Blogs"

[module]
  [module.hugoVersion]
    extended=false
    min = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  [params.theme_config]
    appearance = "auto"
    back_home_text = ".."
    back_top_text = "top"
    date_format = "2006-01-02"
    isListGroupByDate = false
